#!/bin/bash

# Generate release notes for Shopify Spring SDK
# Usage: ./generate-release-notes.sh <version> [previous_version]

VERSION=${1:-"1.0.0"}
PREVIOUS_VERSION=${2:-""}
REPO="astroryan/shopify-sdk-graphql-java"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}🏷️ Generating release notes for v${VERSION}${NC}"

# Create release notes file
cat > release_notes.md << EOF
## 🚀 Shopify Spring SDK v${VERSION}

### 📦 Installation

Add to your \`build.gradle\`:
\`\`\`gradle
repositories {
    maven {
        url = uri("https://maven.pkg.github.com/astroryan/shopify-sdk-graphql-java")
        credentials {
            username = project.findProperty("gpr.user") ?: System.getenv("GITHUB_ACTOR")
            password = project.findProperty("gpr.key") ?: System.getenv("GITHUB_TOKEN")
        }
    }
}

dependencies {
    implementation 'com.shopify:shopify-spring-sdk:${VERSION}'
}
\`\`\`

### 🔧 Configuration

\`\`\`yaml
shopify:
  # Private App Token (Recommended)
  admin-api-access-token: \${SHOPIFY_ACCESS_TOKEN}
  api-version: "2025-07"
  
  # Optional logging
  logging:
    level: INFO
    http-requests: false
\`\`\`

### 📋 Changes in this release

EOF

# If previous version is provided, get commit differences
if [ -n "$PREVIOUS_VERSION" ]; then
    echo -e "${YELLOW}📝 Generating changelog from v${PREVIOUS_VERSION} to v${VERSION}${NC}"
    
    # Get commits between versions
    if git rev-parse "v${PREVIOUS_VERSION}" >/dev/null 2>&1; then
        echo "#### 🔄 Commits since v${PREVIOUS_VERSION}:" >> release_notes.md
        echo "" >> release_notes.md
        
        git log v${PREVIOUS_VERSION}..HEAD --oneline --pretty=format:"- %s (%h)" >> release_notes.md
        echo "" >> release_notes.md
        echo "" >> release_notes.md
    else
        echo -e "${YELLOW}⚠️ Previous version tag v${PREVIOUS_VERSION} not found${NC}"
    fi
fi

# Add standard sections
cat >> release_notes.md << EOF
#### ✨ Highlights

- 🔧 Production-ready release with full testing
- ✅ Compatible with Shopify Admin API 2025-07
- 🚀 Optimized performance and reliability
- 📚 Updated documentation and examples

#### 📋 Version Compatibility

| Component | Version |
|-----------|---------|
| Java | 17+ |
| Spring Boot | 3.2.0+ |
| Shopify API | 2025-07 |
| Gradle | 8.0+ |

### 🧪 Testing

This release has been tested with:
- ✅ Unit tests (100% coverage target)
- ✅ Integration tests (with test Shopify store)
- ✅ Code quality checks (SpotBugs, Checkstyle)
- ✅ Security vulnerability scans

### 📚 Documentation

- 📖 [README](https://github.com/${REPO}/blob/main/README.md)
- 📘 [Publishing Guide](https://github.com/${REPO}/blob/main/PUBLISHING.md)
- 📝 [Full Changelog](https://github.com/${REPO}/blob/main/CHANGELOG.md)
- 🔗 [Shopify API Docs](https://shopify.dev/docs/api/admin-graphql)

### 🙏 Support

- 🐛 [Report Issues](https://github.com/${REPO}/issues)
- 💬 [Discussions](https://github.com/${REPO}/discussions)
- 📧 Questions? Open an issue or discussion

---

🤖 *This release was automatically generated by GitHub Actions*
EOF

echo -e "${GREEN}✅ Release notes generated: release_notes.md${NC}"
echo -e "${BLUE}📄 Preview:${NC}"
echo "----------------------------------------"
head -20 release_notes.md
echo "..."
echo "----------------------------------------"