name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      
    - name: Build with Gradle
      run: |
        cd shopify-spring-sdk
        ./gradlew clean build
        
    - name: Run unit tests
      run: |
        cd shopify-spring-sdk
        ./gradlew test
        
    - name: Generate test report
      if: always()
      run: |
        cd shopify-spring-sdk
        ./gradlew jacocoTestReport
        
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: shopify-spring-sdk/build/reports/tests/test/
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        directory: ./shopify-spring-sdk/build/reports/jacoco/test/
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
        
  integration-test:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      
    - name: Run integration tests
      if: env.SHOPIFY_TEST_STORE_DOMAIN != ''
      run: |
        cd shopify-spring-sdk
        ./gradlew integrationTest
      env:
        SHOPIFY_TEST_STORE_DOMAIN: ${{ secrets.SHOPIFY_TEST_STORE_DOMAIN }}
        SHOPIFY_TEST_ACCESS_TOKEN: ${{ secrets.SHOPIFY_TEST_ACCESS_TOKEN }}
        
  code-quality:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Run SpotBugs
      run: |
        cd shopify-spring-sdk
        ./gradlew spotbugsMain || true
        
    - name: Check code style
      run: |
        cd shopify-spring-sdk
        ./gradlew checkstyleMain || true

  publish:
    runs-on: ubuntu-latest
    needs: [test, integration-test, code-quality]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: read
      packages: write
      
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      
    - name: Publish to GitHub Packages
      run: |
        cd shopify-spring-sdk
        ./gradlew publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}