name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 1.1.0)'
        required: true
        default: '1.1.0'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      
    - name: Build with Gradle
      run: |
        cd shopify-spring-sdk
        ./gradlew clean build
        
    - name: Run unit tests
      run: |
        cd shopify-spring-sdk
        ./gradlew test
        
    - name: Generate test report
      if: always()
      run: |
        cd shopify-spring-sdk
        ./gradlew jacocoTestReport
        
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: shopify-spring-sdk/build/reports/tests/test/
        
    - name: Upload coverage reports
      uses: codecov/codecov-action@v4
      with:
        directory: ./shopify-spring-sdk/build/reports/jacoco/test/
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
        
  integration-test:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      
    - name: Run integration tests
      if: env.SHOPIFY_TEST_STORE_DOMAIN != ''
      run: |
        cd shopify-spring-sdk
        ./gradlew integrationTest
      env:
        SHOPIFY_TEST_STORE_DOMAIN: ${{ secrets.SHOPIFY_TEST_STORE_DOMAIN }}
        SHOPIFY_TEST_ACCESS_TOKEN: ${{ secrets.SHOPIFY_TEST_ACCESS_TOKEN }}
        
  code-quality:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Run SpotBugs
      run: |
        cd shopify-spring-sdk
        ./gradlew spotbugsMain || true
        
    - name: Check code style
      run: |
        cd shopify-spring-sdk
        ./gradlew checkstyleMain || true

  publish:
    runs-on: ubuntu-latest
    needs: [test, code-quality]
    if: >
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      github.event_name == 'release' ||
      github.event_name == 'workflow_dispatch'
    permissions:
      contents: read
      packages: write
      
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      
    - name: Update version if manually triggered
      if: github.event_name == 'workflow_dispatch'
      run: |
        sed -i "s/version = '.*'/version = '${{ github.event.inputs.version }}'/" shopify-spring-sdk/build.gradle
        
    - name: Publish to GitHub Packages
      run: |
        cd shopify-spring-sdk
        ./gradlew publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Create release notes
      if: github.event_name == 'release'
      run: |
        echo "## Shopify Spring SDK ${{ github.event.release.tag_name }}" > release-notes.md
        echo "" >> release-notes.md
        echo "### Installation" >> release-notes.md
        echo "" >> release-notes.md
        echo "Add to your \`build.gradle\`:" >> release-notes.md
        echo "\`\`\`gradle" >> release-notes.md
        echo "repositories {" >> release-notes.md
        echo "    maven {" >> release-notes.md
        echo "        url = uri(\"https://maven.pkg.github.com/astroryan/shopify-sdk-graphql-java\")" >> release-notes.md
        echo "        credentials {" >> release-notes.md
        echo "            username = project.findProperty(\"gpr.user\") ?: System.getenv(\"USERNAME\")" >> release-notes.md
        echo "            password = project.findProperty(\"gpr.key\") ?: System.getenv(\"TOKEN\")" >> release-notes.md
        echo "        }" >> release-notes.md
        echo "    }" >> release-notes.md
        echo "}" >> release-notes.md
        echo "" >> release-notes.md
        echo "dependencies {" >> release-notes.md
        echo "    implementation 'com.shopify:shopify-spring-sdk:${{ github.event.release.tag_name }}'" >> release-notes.md
        echo "}" >> release-notes.md
        echo "\`\`\`" >> release-notes.md
        
    - name: Update release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v2
      with:
        files: release-notes.md
        append_body: true